export let products = [
  // Zapatos
  {
    id: 1,
    nombre: "Zapato deportivo",
    descripcion: "Cómodos para correr",
    precio: 59.99,
    imagen: "zapato_deportivo.jpg",
    categoria: "Zapatos",
  },
  {
    id: 2,
    nombre: "Zapato casual",
    descripcion: "Estilo y confort para el día a día",
    precio: 49.99,
    imagen: "zapato_casual.jpg",
    categoria: "Zapatos",
  },
  {
    id: 3,
    nombre: "Botas de trabajo",
    descripcion: "Resistentes para cualquier obra",
    precio: 89.99,
    imagen: "botas_trabajo.jpg",
    categoria: "Zapatos",
  },
  {
    id: 4,
    nombre: "Sandalias",
    descripcion: "Ideales para el verano",
    precio: 29.99,
    imagen: "sandalias.jpg",
    categoria: "Zapatos",
  },
  {
    id: 5,
    nombre: "Mocasines",
    descripcion: "Elegancia clásica",
    precio: 79.99,
    imagen: "mocasines.jpg",
    categoria: "Zapatos",
  },

  // Camisas
  {
    id: 6,
    nombre: "Camisa de vestir",
    descripcion: "Perfecta para eventos formales",
    precio: 39.99,
    imagen: "camisa_vestir.jpg",
    categoria: "Camisas",
  },
  {
    id: 7,
    nombre: "Camisa polo",
    descripcion: "Casual pero arreglado",
    precio: 34.99,
    imagen: "camisa_polo.jpg",
    categoria: "Camisas",
  },
  {
    id: 8,
    nombre: "Camisa de manga larga",
    descripcion: "Versátil para todas las estaciones",
    precio: 29.99,
    imagen: "camisa_manga_larga.jpg",
    categoria: "Camisas",
  },
  {
    id: 9,
    nombre: "Camisa de franela",
    descripcion: "Calidez y comodidad",
    precio: 24.99,
    imagen: "camisa_franela.jpg",
    categoria: "Camisas",
  },
  {
    id: 10,
    nombre: "Camiseta básica",
    descripcion: "Un básico indispensable",
    precio: 14.99,
    imagen: "camiseta_basica.jpg",
    categoria: "Camisas",
  },

  // Pantalones
  {
    id: 11,
    nombre: "Jeans",
    descripcion: "Resistentes y siempre de moda",
    precio: 49.99,
    imagen: "jeans.jpg",
    categoria: "Pantalones",
  },
  {
    id: 12,
    nombre: "Pantalones chinos",
    descripcion: "Elegancia casual",
    precio: 44.99,
    imagen: "pantalones_chinos.jpg",
    categoria: "Pantalones",
  },
  {
    id: 13,
    nombre: "Pantalones de vestir",
    descripcion: "Formalidad y estilo",
    precio: 59.99,
    imagen: "pantalones_vestir.jpg",
    categoria: "Pantalones",
  },
  {
    id: 14,
    nombre: "Pantalones cargo",
    descripcion: "Comodidad y capacidad",
    precio: 39.99,
    imagen: "pantalones_cargo.jpg",
    categoria: "Pantalones",
  },
  {
    id: 15,
    nombre: "Shorts",
    descripcion: "Frescura para los días calurosos",
    precio: 19.99,
    imagen: "shorts.jpg",
    categoria: "Pantalones",
  },

  // Abrigos
  {
    id: 16,
    nombre: "Abrigo de lana",
    descripcion: "Elegante y abrigado",
    precio: 129.99,
    imagen: "abrigo_lana.jpg",
    categoria: "Abrigos",
  },
  {
    id: 17,
    nombre: "Chaqueta impermeable",
    descripcion: "Protección contra la lluvia",
    precio: 79.99,
    imagen: "chaqueta_impermeable.jpg",
    categoria: "Abrigos",
  },
  {
    id: 18,
    nombre: "Parka con capucha",
    descripcion: "Estilo urbano y funcional",
    precio: 109.99,
    imagen: "parka_capucha.jpg",
    categoria: "Abrigos",
  },
  {
    id: 19,
    nombre: "Chaleco acolchado",
    descripcion: "Calidez sin mangas",
    precio: 49.99,
    imagen: "chaleco_acolchado.jpg",
    categoria: "Abrigos",
  },
  {
    id: 19,
    nombre: "Abrigo de Algodon",
    descripcion: "Muy Calido",
    precio: 29.99,
    imagen: "abrigo_algodon.jpg",
    categoria: "Abrigos",
  },
];
